name: GhostStrings iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: "5.9"

    - name: Resolve Dependencies
      run: swift package resolve

    - name: Build Library
      run: swift build -v

    - name: Run Tests
      run: swift test -v
